#ifndef COMPONENT_TYPE_H_INCLUDED
#define COMPONENT_TYPE_H_INCLUDED

#ifdef NET_PHYSICS_CLIENT
	#undef COMPONENT_TYPE_H_INCLUDED	
	#pragma once
	#include "NetPhysicsClient.h"
#endif /* NET_PHYSICS_CLIENT */

namespace NetPhysics {
	enum ComponentType {
#ifdef NET_PHYSICS_SERVER
		CLIENT_COMPONENT,
		PHYSICS_COMPONENT,
		PLAYER_STATE_COMPONENT,
		TIMER_COMPONENT,
		SCRIPT_COMPONENT,
#endif /* NET_PHYSICS_SERVER */
		NETWORK_COMPONENT,
		REPLICATION_COMPONENT,
		NUM_COMPONENT_TYPES
	};
}

#endif /* COMPONENT_TYPE_H_INCLUDED */